/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: data.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "data.pb-c.h"
void   subid__init
                     (Subid         *message)
{
  static const Subid init_value = SUBID__INIT;
  *message = init_value;
}
size_t subid__get_packed_size
                     (const Subid *message)
{
  assert(message->base.descriptor == &subid__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t subid__pack
                     (const Subid *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &subid__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t subid__pack_to_buffer
                     (const Subid *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &subid__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Subid *
       subid__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Subid *)
     protobuf_c_message_unpack (&subid__descriptor,
                                allocator, len, data);
}
void   subid__free_unpacked
                     (Subid *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &subid__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ack__init
                     (Ack         *message)
{
  static const Ack init_value = ACK__INIT;
  *message = init_value;
}
size_t ack__get_packed_size
                     (const Ack *message)
{
  assert(message->base.descriptor == &ack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ack__pack
                     (const Ack *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ack__pack_to_buffer
                     (const Ack *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ack *
       ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ack *)
     protobuf_c_message_unpack (&ack__descriptor,
                                allocator, len, data);
}
void   ack__free_unpacked
                     (Ack *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gpio__init
                     (Gpio         *message)
{
  static const Gpio init_value = GPIO__INIT;
  *message = init_value;
}
size_t gpio__get_packed_size
                     (const Gpio *message)
{
  assert(message->base.descriptor == &gpio__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gpio__pack
                     (const Gpio *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gpio__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gpio__pack_to_buffer
                     (const Gpio *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gpio__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gpio *
       gpio__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gpio *)
     protobuf_c_message_unpack (&gpio__descriptor,
                                allocator, len, data);
}
void   gpio__free_unpacked
                     (Gpio *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gpio__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   voltage__init
                     (Voltage         *message)
{
  static const Voltage init_value = VOLTAGE__INIT;
  *message = init_value;
}
size_t voltage__get_packed_size
                     (const Voltage *message)
{
  assert(message->base.descriptor == &voltage__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t voltage__pack
                     (const Voltage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &voltage__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t voltage__pack_to_buffer
                     (const Voltage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &voltage__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Voltage *
       voltage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Voltage *)
     protobuf_c_message_unpack (&voltage__descriptor,
                                allocator, len, data);
}
void   voltage__free_unpacked
                     (Voltage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &voltage__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gsensor__accel__init
                     (Gsensor__Accel         *message)
{
  static const Gsensor__Accel init_value = GSENSOR__ACCEL__INIT;
  *message = init_value;
}
void   gsensor__gyro__init
                     (Gsensor__Gyro         *message)
{
  static const Gsensor__Gyro init_value = GSENSOR__GYRO__INIT;
  *message = init_value;
}
void   gsensor__init
                     (Gsensor         *message)
{
  static const Gsensor init_value = GSENSOR__INIT;
  *message = init_value;
}
size_t gsensor__get_packed_size
                     (const Gsensor *message)
{
  assert(message->base.descriptor == &gsensor__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gsensor__pack
                     (const Gsensor *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gsensor__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gsensor__pack_to_buffer
                     (const Gsensor *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gsensor__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gsensor *
       gsensor__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gsensor *)
     protobuf_c_message_unpack (&gsensor__descriptor,
                                allocator, len, data);
}
void   gsensor__free_unpacked
                     (Gsensor *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gsensor__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gps__init
                     (Gps         *message)
{
  static const Gps init_value = GPS__INIT;
  *message = init_value;
}
size_t gps__get_packed_size
                     (const Gps *message)
{
  assert(message->base.descriptor == &gps__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gps__pack
                     (const Gps *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gps__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gps__pack_to_buffer
                     (const Gps *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gps__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gps *
       gps__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gps *)
     protobuf_c_message_unpack (&gps__descriptor,
                                allocator, len, data);
}
void   gps__free_unpacked
                     (Gps *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gps__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vehic__init
                     (Vehic         *message)
{
  static const Vehic init_value = VEHIC__INIT;
  *message = init_value;
}
size_t vehic__get_packed_size
                     (const Vehic *message)
{
  assert(message->base.descriptor == &vehic__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vehic__pack
                     (const Vehic *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vehic__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vehic__pack_to_buffer
                     (const Vehic *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vehic__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vehic *
       vehic__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vehic *)
     protobuf_c_message_unpack (&vehic__descriptor,
                                allocator, len, data);
}
void   vehic__free_unpacked
                     (Vehic *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vehic__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ecu__init
                     (Ecu         *message)
{
  static const Ecu init_value = ECU__INIT;
  *message = init_value;
}
size_t ecu__get_packed_size
                     (const Ecu *message)
{
  assert(message->base.descriptor == &ecu__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ecu__pack
                     (const Ecu *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ecu__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ecu__pack_to_buffer
                     (const Ecu *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ecu__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ecu *
       ecu__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ecu *)
     protobuf_c_message_unpack (&ecu__descriptor,
                                allocator, len, data);
}
void   ecu__free_unpacked
                     (Ecu *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ecu__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   iccard__init
                     (Iccard         *message)
{
  static const Iccard init_value = ICCARD__INIT;
  *message = init_value;
}
size_t iccard__get_packed_size
                     (const Iccard *message)
{
  assert(message->base.descriptor == &iccard__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t iccard__pack
                     (const Iccard *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &iccard__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t iccard__pack_to_buffer
                     (const Iccard *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &iccard__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Iccard *
       iccard__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Iccard *)
     protobuf_c_message_unpack (&iccard__descriptor,
                                allocator, len, data);
}
void   iccard__free_unpacked
                     (Iccard *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &iccard__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lcd__msg__init
                     (Lcd__Msg         *message)
{
  static const Lcd__Msg init_value = LCD__MSG__INIT;
  *message = init_value;
}
void   lcd__button__init
                     (Lcd__Button         *message)
{
  static const Lcd__Button init_value = LCD__BUTTON__INIT;
  *message = init_value;
}
void   lcd__init
                     (Lcd         *message)
{
  static const Lcd init_value = LCD__INIT;
  *message = init_value;
}
size_t lcd__get_packed_size
                     (const Lcd *message)
{
  assert(message->base.descriptor == &lcd__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lcd__pack
                     (const Lcd *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lcd__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lcd__pack_to_buffer
                     (const Lcd *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lcd__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Lcd *
       lcd__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Lcd *)
     protobuf_c_message_unpack (&lcd__descriptor,
                                allocator, len, data);
}
void   lcd__free_unpacked
                     (Lcd *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lcd__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   printer__init
                     (Printer         *message)
{
  static const Printer init_value = PRINTER__INIT;
  *message = init_value;
}
size_t printer__get_packed_size
                     (const Printer *message)
{
  assert(message->base.descriptor == &printer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t printer__pack
                     (const Printer *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &printer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t printer__pack_to_buffer
                     (const Printer *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &printer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Printer *
       printer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Printer *)
     protobuf_c_message_unpack (&printer__descriptor,
                                allocator, len, data);
}
void   printer__free_unpacked
                     (Printer *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &printer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   can__init
                     (Can         *message)
{
  static const Can init_value = CAN__INIT;
  *message = init_value;
}
size_t can__get_packed_size
                     (const Can *message)
{
  assert(message->base.descriptor == &can__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t can__pack
                     (const Can *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &can__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t can__pack_to_buffer
                     (const Can *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &can__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Can *
       can__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Can *)
     protobuf_c_message_unpack (&can__descriptor,
                                allocator, len, data);
}
void   can__free_unpacked
                     (Can *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &can__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   flash__init
                     (Flash         *message)
{
  static const Flash init_value = FLASH__INIT;
  *message = init_value;
}
size_t flash__get_packed_size
                     (const Flash *message)
{
  assert(message->base.descriptor == &flash__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t flash__pack
                     (const Flash *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &flash__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t flash__pack_to_buffer
                     (const Flash *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &flash__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Flash *
       flash__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Flash *)
     protobuf_c_message_unpack (&flash__descriptor,
                                allocator, len, data);
}
void   flash__free_unpacked
                     (Flash *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &flash__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor subid__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Subid, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subdata",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Subid, n_subdata),
    offsetof(Subid, subdata),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned subid__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = subdata */
};
static const ProtobufCIntRange subid__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor subid__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Subid",
  "Subid",
  "Subid",
  "",
  sizeof(Subid),
  2,
  subid__field_descriptors,
  subid__field_indices_by_name,
  1,  subid__number_ranges,
  (ProtobufCMessageInit) subid__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ack__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Ack, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rev1",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Ack, has_rev1),
    offsetof(Ack, rev1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ack__field_indices_by_name[] = {
  1,   /* field[1] = rev1 */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange ack__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ack__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ack",
  "Ack",
  "Ack",
  "",
  sizeof(Ack),
  2,
  ack__field_descriptors,
  ack__field_indices_by_name,
  1,  ack__number_ranges,
  (ProtobufCMessageInit) ack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gpio__field_descriptors[2] =
{
  {
    "gpio",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Gpio, gpio),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Gpio, has_value),
    offsetof(Gpio, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gpio__field_indices_by_name[] = {
  0,   /* field[0] = gpio */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange gpio__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor gpio__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Gpio",
  "Gpio",
  "Gpio",
  "",
  sizeof(Gpio),
  2,
  gpio__field_descriptors,
  gpio__field_indices_by_name,
  1,  gpio__number_ranges,
  (ProtobufCMessageInit) gpio__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor voltage__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Voltage, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Voltage, has_value),
    offsetof(Voltage, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned voltage__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange voltage__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor voltage__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Voltage",
  "Voltage",
  "Voltage",
  "",
  sizeof(Voltage),
  2,
  voltage__field_descriptors,
  voltage__field_indices_by_name,
  1,  voltage__number_ranges,
  (ProtobufCMessageInit) voltage__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gsensor__accel__field_descriptors[3] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Gsensor__Accel, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Gsensor__Accel, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Gsensor__Accel, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gsensor__accel__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
  2,   /* field[2] = z */
};
static const ProtobufCIntRange gsensor__accel__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor gsensor__accel__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Gsensor.accel",
  "Accel",
  "Gsensor__Accel",
  "",
  sizeof(Gsensor__Accel),
  3,
  gsensor__accel__field_descriptors,
  gsensor__accel__field_indices_by_name,
  1,  gsensor__accel__number_ranges,
  (ProtobufCMessageInit) gsensor__accel__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gsensor__gyro__field_descriptors[3] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Gsensor__Gyro, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Gsensor__Gyro, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Gsensor__Gyro, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gsensor__gyro__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
  2,   /* field[2] = z */
};
static const ProtobufCIntRange gsensor__gyro__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor gsensor__gyro__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Gsensor.gyro",
  "Gyro",
  "Gsensor__Gyro",
  "",
  sizeof(Gsensor__Gyro),
  3,
  gsensor__gyro__field_descriptors,
  gsensor__gyro__field_indices_by_name,
  1,  gsensor__gyro__number_ranges,
  (ProtobufCMessageInit) gsensor__gyro__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gsensor__field_descriptors[3] =
{
  {
    "interval",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Gsensor, interval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "a",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Gsensor, a),
    &gsensor__accel__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "g",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Gsensor, g),
    &gsensor__gyro__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gsensor__field_indices_by_name[] = {
  1,   /* field[1] = a */
  2,   /* field[2] = g */
  0,   /* field[0] = interval */
};
static const ProtobufCIntRange gsensor__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor gsensor__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Gsensor",
  "Gsensor",
  "Gsensor",
  "",
  sizeof(Gsensor),
  3,
  gsensor__field_descriptors,
  gsensor__field_indices_by_name,
  1,  gsensor__number_ranges,
  (ProtobufCMessageInit) gsensor__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gps__field_descriptors[1] =
{
  {
    "nmea",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Gps, nmea),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gps__field_indices_by_name[] = {
  0,   /* field[0] = nmea */
};
static const ProtobufCIntRange gps__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor gps__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Gps",
  "Gps",
  "Gps",
  "",
  sizeof(Gps),
  1,
  gps__field_descriptors,
  gps__field_indices_by_name,
  1,  gps__number_ranges,
  (ProtobufCMessageInit) gps__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vehic__field_descriptors[4] =
{
  {
    "interval",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vehic, interval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "acc",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Vehic, has_acc),
    offsetof(Vehic, acc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "total",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Vehic, has_total),
    offsetof(Vehic, total),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pulse",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Vehic, has_pulse),
    offsetof(Vehic, pulse),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vehic__field_indices_by_name[] = {
  1,   /* field[1] = acc */
  0,   /* field[0] = interval */
  3,   /* field[3] = pulse */
  2,   /* field[2] = total */
};
static const ProtobufCIntRange vehic__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor vehic__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Vehic",
  "Vehic",
  "Vehic",
  "",
  sizeof(Vehic),
  4,
  vehic__field_descriptors,
  vehic__field_indices_by_name,
  1,  vehic__number_ranges,
  (ProtobufCMessageInit) vehic__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ecu__field_descriptors[11] =
{
  {
    "mileage",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Ecu, has_mileage),
    offsetof(Ecu, mileage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "speed",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Ecu, has_speed),
    offsetof(Ecu, speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rotate",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Ecu, has_rotate),
    offsetof(Ecu, rotate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "left_oil_percent",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Ecu, has_left_oil_percent),
    offsetof(Ecu, left_oil_percent),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "voltage",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Ecu, has_voltage),
    offsetof(Ecu, voltage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "oil_mass",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Ecu, has_oil_mass),
    offsetof(Ecu, oil_mass),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fault_lamp",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Ecu, has_fault_lamp),
    offsetof(Ecu, fault_lamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "oil_temp",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Ecu, has_oil_temp),
    offsetof(Ecu, oil_temp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "left_oil_warn",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Ecu, has_left_oil_warn),
    offsetof(Ecu, left_oil_warn),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vin",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ecu, vin),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "interval",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Ecu, has_interval),
    offsetof(Ecu, interval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ecu__field_indices_by_name[] = {
  6,   /* field[6] = fault_lamp */
  10,   /* field[10] = interval */
  3,   /* field[3] = left_oil_percent */
  8,   /* field[8] = left_oil_warn */
  0,   /* field[0] = mileage */
  5,   /* field[5] = oil_mass */
  7,   /* field[7] = oil_temp */
  2,   /* field[2] = rotate */
  1,   /* field[1] = speed */
  9,   /* field[9] = vin */
  4,   /* field[4] = voltage */
};
static const ProtobufCIntRange ecu__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor ecu__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ecu",
  "Ecu",
  "Ecu",
  "",
  sizeof(Ecu),
  11,
  ecu__field_descriptors,
  ecu__field_indices_by_name,
  1,  ecu__number_ranges,
  (ProtobufCMessageInit) ecu__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor iccard__field_descriptors[3] =
{
  {
    "ic",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Iccard, has_ic),
    offsetof(Iccard, ic),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addr",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Iccard, has_addr),
    offsetof(Iccard, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "insert",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Iccard, has_insert),
    offsetof(Iccard, insert),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned iccard__field_indices_by_name[] = {
  1,   /* field[1] = addr */
  0,   /* field[0] = ic */
  2,   /* field[2] = insert */
};
static const ProtobufCIntRange iccard__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor iccard__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Iccard",
  "Iccard",
  "Iccard",
  "",
  sizeof(Iccard),
  3,
  iccard__field_descriptors,
  iccard__field_indices_by_name,
  1,  iccard__number_ranges,
  (ProtobufCMessageInit) iccard__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lcd__msg__field_descriptors[5] =
{
  {
    "page",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Lcd__Msg, page),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "column",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Lcd__Msg, column),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wide",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Lcd__Msg, wide),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "high",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Lcd__Msg, high),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "screen",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Lcd__Msg, screen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lcd__msg__field_indices_by_name[] = {
  1,   /* field[1] = column */
  3,   /* field[3] = high */
  0,   /* field[0] = page */
  4,   /* field[4] = screen */
  2,   /* field[2] = wide */
};
static const ProtobufCIntRange lcd__msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor lcd__msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Lcd.msg",
  "Msg",
  "Lcd__Msg",
  "",
  sizeof(Lcd__Msg),
  5,
  lcd__msg__field_descriptors,
  lcd__msg__field_indices_by_name,
  1,  lcd__msg__number_ranges,
  (ProtobufCMessageInit) lcd__msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lcd__button__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Lcd__Button, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Lcd__Button, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lcd__button__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange lcd__button__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor lcd__button__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Lcd.button",
  "Button",
  "Lcd__Button",
  "",
  sizeof(Lcd__Button),
  2,
  lcd__button__field_descriptors,
  lcd__button__field_indices_by_name,
  1,  lcd__button__number_ranges,
  (ProtobufCMessageInit) lcd__button__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lcd__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Lcd, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Lcd, key),
    &lcd__button__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Lcd, data),
    &lcd__msg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lcd__field_indices_by_name[] = {
  2,   /* field[2] = data */
  1,   /* field[1] = key */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange lcd__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor lcd__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Lcd",
  "Lcd",
  "Lcd",
  "",
  sizeof(Lcd),
  3,
  lcd__field_descriptors,
  lcd__field_indices_by_name,
  1,  lcd__number_ranges,
  (ProtobufCMessageInit) lcd__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor printer__field_descriptors[1] =
{
  {
    "print",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Printer, print),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned printer__field_indices_by_name[] = {
  0,   /* field[0] = print */
};
static const ProtobufCIntRange printer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor printer__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Printer",
  "Printer",
  "Printer",
  "",
  sizeof(Printer),
  1,
  printer__field_descriptors,
  printer__field_indices_by_name,
  1,  printer__number_ranges,
  (ProtobufCMessageInit) printer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor can__field_descriptors[3] =
{
  {
    "canid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Can, canid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Can, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Can, has_data),
    offsetof(Can, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned can__field_indices_by_name[] = {
  0,   /* field[0] = canid */
  2,   /* field[2] = data */
  1,   /* field[1] = id */
};
static const ProtobufCIntRange can__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor can__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Can",
  "Can",
  "Can",
  "",
  sizeof(Can),
  3,
  can__field_descriptors,
  can__field_indices_by_name,
  1,  can__number_ranges,
  (ProtobufCMessageInit) can__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor flash__field_descriptors[3] =
{
  {
    "offset",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Flash, offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Flash, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Flash, has_data),
    offsetof(Flash, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned flash__field_indices_by_name[] = {
  2,   /* field[2] = data */
  0,   /* field[0] = offset */
  1,   /* field[1] = size */
};
static const ProtobufCIntRange flash__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor flash__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Flash",
  "Flash",
  "Flash",
  "",
  sizeof(Flash),
  3,
  flash__field_descriptors,
  flash__field_indices_by_name,
  1,  flash__number_ranges,
  (ProtobufCMessageInit) flash__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue ioc__enum_values_by_number[12] =
{
  { "SET", "IOC__SET", 1 },
  { "GET", "IOC__GET", 2 },
  { "DATA", "IOC__DATA", 3 },
  { "SEND", "IOC__SEND", 4 },
  { "FILTER", "IOC__FILTER", 5 },
  { "POWERON", "IOC__POWERON", 6 },
  { "LEDON", "IOC__LEDON", 7 },
  { "INIT", "IOC__INIT", 8 },
  { "CLEAR", "IOC__CLEAR", 9 },
  { "REBOOT", "IOC__REBOOT", 10 },
  { "LEDOFF", "IOC__LEDOFF", 11 },
  { "PWROFF", "IOC__PWROFF", 12 },
};
static const ProtobufCIntRange ioc__value_ranges[] = {
{1, 0},{0, 12}
};
static const ProtobufCEnumValueIndex ioc__enum_values_by_name[12] =
{
  { "CLEAR", 8 },
  { "DATA", 2 },
  { "FILTER", 4 },
  { "GET", 1 },
  { "INIT", 7 },
  { "LEDOFF", 10 },
  { "LEDON", 6 },
  { "POWERON", 5 },
  { "PWROFF", 11 },
  { "REBOOT", 9 },
  { "SEND", 3 },
  { "SET", 0 },
};
const ProtobufCEnumDescriptor ioc__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "IOC",
  "IOC",
  "IOC",
  "",
  12,
  ioc__enum_values_by_number,
  12,
  ioc__enum_values_by_name,
  1,
  ioc__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
