/*!
 * \file      Commissioning.h
 *
 * \brief     End device commissioning parameters
 *
 * \copyright Revised BSD License, see section \ref LICENSE.
 *
 * \code
 *                ______                              _
 *               / _____)             _              | |
 *              ( (____  _____ ____ _| |_ _____  ____| |__
 *               \____ \| ___ |    (_   _) ___ |/ ___)  _ \
 *               _____) ) ____| | | || |_| ____( (___| | | |
 *              (______/|_____)_|_|_| \__)_____)\____)_| |_|
 *              (C)2013-2017 Semtech
 *
 * \endcode
 *
 * \author    Miguel Luis ( Semtech )
 *
 * \author    Gregory Cristian ( Semtech )
 */
#ifndef __LORA_COMMISSIONING_H__
#define __LORA_COMMISSIONING_H__

/*!
 ******************************************************************************
 ********************************** WARNING ***********************************
 ******************************************************************************
  The crypto-element implementation supports both 1.0.x and 1.1.x LoRaWAN 
  versions of the specification.
  Thus it has been decided to use the 1.1.x keys and EUI name definitions.
  The below table shows the names equivalence between versions:
               +-------------------+-------------------------+
               |       1.0.x       |          1.1.x          |
               +===================+=========================+
               | LORAWAN_DEVICE_EUI| LORAWAN_DEVICE_EUI      |
               +-------------------+-------------------------+
               | LORAWAN_APP_EUI   | LORAWAN_JOIN_EUI        |
               +-------------------+-------------------------+
               | N/A               | LORAWAN_APP_KEY         |
               +-------------------+-------------------------+
               | LORAWAN_APP_KEY   | LORAWAN_NWK_KEY         |
               +-------------------+-------------------------+
               | LORAWAN_NWK_S_KEY | LORAWAN_F_NWK_S_INT_KEY |
               +-------------------+-------------------------+
               | LORAWAN_NWK_S_KEY | LORAWAN_S_NWK_S_INT_KEY |
               +-------------------+-------------------------+
               | LORAWAN_NWK_S_KEY | LORAWAN_NWK_S_ENC_KEY   |
               +-------------------+-------------------------+
               | LORAWAN_APP_S_KEY | LORAWAN_APP_S_KEY       |
               +-------------------+-------------------------+
 ******************************************************************************
 ******************************************************************************
 ******************************************************************************
 */
#include "uart_driver.h"
#define MAIN_CLASS_A   0              
#define MAIN_CLASS_B   0         
#define MAIN_CLASS_C   0            
#define MAIN_TX        0      
#define MAIN_RX		   0  
#define MAIN_PP        0    
#define MAIN_SDK       1    
#define printf(format, ...) lprint(format,  ##__VA_ARGS__)

/*!
 * When set to 1 the application uses the Over-the-Air activation procedure
 * When set to 0 the application uses the Personalization activation procedure
 */
#define OVER_THE_AIR_ACTIVATION                            1

/*!
 * When set to 1 the application uses the static multicast method procedure
 * When set to 0 the application uses the dynamic multicast method procedure
 */
#define MC_STATIC_METHOD                            1

/*!
 * When using ABP activation the MAC layer must know in advance to which server
 * version it will be connected.
 */
#define ABP_ACTIVATION_LRWAN_VERSION_V10x                  0x01000300 // 1.0.3.0

#define ABP_ACTIVATION_LRWAN_VERSION                       ABP_ACTIVATION_LRWAN_VERSION_V10x

/*!
 * Indicates if the end-device is to be connected to a private or public network
 */
#define LORAWAN_PUBLIC_NETWORK                             true

/*!
 * IEEE Organizationally Unique Identifier ( OUI ) (big endian)
 * \remark This is unique to a company or organization
 */
#define IEEE_OUI                                           0x00, 0x00, 0x00

/*!
 * Mote device IEEE EUI (big endian)
 *
 * \remark In this application the value is automatically generated by calling
 *         BoardGetUniqueId function
 */
//#define LORAWAN_DEVICE_EUI                                 { IEEE_OUI, 0x00, 0x00, 0x00, 0x00, 0x00 }
//#define LORAWAN_DEVICE_EUI                                 {0xD8 ,0x96 ,0xE0 ,0x00, 0x1C, 0x00, 0x00, 0x69 }
#define LORAWAN_DEVICE_EUI                                 {0xd8, 0x96, 0xe0, 0xff, 0xff, 0x01,0x02, 0x5d}

/*!
 * App/Join server IEEE EUI (big endian)
 */
//#define LORAWAN_JOIN_EUI                                   { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }
//#define LORAWAN_JOIN_EUI                                    {0xD8, 0x96,0xE0,0xE0,0x00,0x00,0x37,0xFD}
#define LORAWAN_JOIN_EUI                                    {0xd8, 0x96, 0xe0, 0xe0, 0x00, 0x00, 0x14, 0x6c}

/*!
 * Application root key
 * WARNING: NOT USED FOR 1.0.x DEVICES
 */
//#define LORAWAN_APP_KEY                                    { 0x2B, 0x7E, 0x15, 0x16, 0x28, 0xAE, 0xD2, 0xA6, 0xAB, 0xF7, 0x15, 0x88, 0x09, 0xCF, 0x4F, 0x3C }
//#define LORAWAN_APP_KEY                                     {0x29,0xF6,0xC7,0xBE,0x72,0x0C,0x55,0x51,0x29,0x84,0x4D,0x17,0xE4,0x68,0xE7,0xB7}
//#define LORAWAN_APP_KEY                                      { 0x2E, 0xD8, 0x65, 0xA4, 0x32, 0xB2, 0x34, 0xAD, 0x94, 0xDA, 0x14, 0xEA, 0x74, 0x1C, 0xA3, 0xFE }
//#define LORAWAN_APP_KEY  {0x96,0x6E,0x1E,0xB3,0xC8,0xBA,0x0D,0x0E,0x2A,0x07,0xEE,0xB2,0x8D,0x97,0x30,0x15}
#define LORAWAN_APP_KEY    {0xFB,0x19,0xD6,0x5D,0x62,0xBA,0x01,0x9E,0xE6,0xD7,0xF7,0xA5,0x12,0x9D,0xBE,0x39}
/*!
 * Network root key
 * WARNING: FOR 1.0.x DEVICES IT IS THE \ref LORAWAN_APP_KEY
 */
//#define LORAWAN_NWK_KEY                                    { 0x2B, 0x7E, 0x15, 0x16, 0x28, 0xAE, 0xD2, 0xA6, 0xAB, 0xF7, 0x15, 0x88, 0x09, 0xCF, 0x4F, 0x3C }
//#define LORAWAN_NWK_KEY                                     {0x29,0xF6,0xC7,0xBE,0x72,0x0C,0x55,0x51,0x29,0x84,0x4D,0x17,0xE4,0x68,0xE7,0xB7}
#define LORAWAN_NWK_KEY   {0xFB,0x19,0xD6,0x5D,0x62,0xBA,0x01,0x9E,0xE6,0xD7,0xF7,0xA5,0x12,0x9D,0xBE,0x39}

/*!
 * Current network ID
 */
#define LORAWAN_NETWORK_ID                                 ( uint32_t )0

/*!
 * When set to 1 DevEui is LORAWAN_DEVICE_EUI
 * When set to 0 DevEui is automatically generated by calling
 *         BoardGetUniqueId function
 */
#define STATIC_DEVICE_EUI                     1

/*!
 * When set to 1 DevAdd is LORAWAN_DEVICE_ADDRESS
 * When set to 0 DevAdd is automatically generated using
 *         a pseudo random generator seeded with a value derived from
 *         BoardUniqueId value
 */
#define STATIC_DEVICE_ADDRESS                     0
/*!
 * Device address on the network (big endian)
 *
 * \remark In this application the value is automatically generated using
 *         a pseudo random generator seeded with a value derived from
 *         BoardUniqueId value if LORAWAN_DEVICE_ADDRESS is set to 0
 */
//#define LORAWAN_DEVICE_ADDRESS                             ( uint32_t )0x00000000
#define LORAWAN_DEVICE_ADDRESS                               ( uint32_t )0x665C2510
/*!
 * Forwarding Network session integrity key
 * WARNING: NWK_S_KEY FOR 1.0.x DEVICES
 */
#define LORAWAN_F_NWK_S_INT_KEY                            { 0x2B, 0x7E, 0x15, 0x16, 0x28, 0xAE, 0xD2, 0xA6, 0xAB, 0xF7, 0x15, 0x88, 0x09, 0xCF, 0x4F, 0x3C }

/*!
 * Serving Network session integrity key
 * WARNING: NOT USED FOR 1.0.x DEVICES. MUST BE THE SAME AS \ref LORAWAN_F_NWK_S_INT_KEY
 */
#define LORAWAN_S_NWK_S_INT_KEY                            { 0x2B, 0x7E, 0x15, 0x16, 0x28, 0xAE, 0xD2, 0xA6, 0xAB, 0xF7, 0x15, 0x88, 0x09, 0xCF, 0x4F, 0x3C }

/*!
 * Network session encryption key
 * WARNING: NOT USED FOR 1.0.x DEVICES. MUST BE THE SAME AS \ref LORAWAN_F_NWK_S_INT_KEY
 */
#define LORAWAN_NWK_S_ENC_KEY                              { 0x2B, 0x7E, 0x15, 0x16, 0x28, 0xAE, 0xD2, 0xA6, 0xAB, 0xF7, 0x15, 0x88, 0x09, 0xCF, 0x4F, 0x3C }

/*!
 * Application session key
 */
#define LORAWAN_APP_S_KEY                                  { 0x2B, 0x7E, 0x15, 0x16, 0x28, 0xAE, 0xD2, 0xA6, 0xAB, 0xF7, 0x15, 0x88, 0x09, 0xCF, 0x4F, 0x3C }

#endif // __LORA_COMMISSIONING_H__

/*!
 * Multicast static addr
 */
#define LORAWAN_MC_ADDR_0   0x00000000
#define LORAWAN_MC_KEY_0    { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }
#define LORAWAN_MC_DR_0       2
#define LORAWAN_MC_PERIOD_0   3

#define LORAWAN_MC_ADDR_1   0x00000000
#define LORAWAN_MC_KEY_1    { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }
#define LORAWAN_MC_DR_1       2
#define LORAWAN_MC_PERIOD_1   3

#define LORAWAN_MC_ADDR_2   0x00000000
#define LORAWAN_MC_KEY_2    { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }
#define LORAWAN_MC_DR_2       2
#define LORAWAN_MC_PERIOD_2   3

#define LORAWAN_MC_ADDR_3   0x00000000
#define LORAWAN_MC_KEY_3    { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 }
#define LORAWAN_MC_DR_3       2
#define LORAWAN_MC_PERIOD_3   3

/*!
 * Multicast static root key
 */
 #define LORAWAN_MC_GEN_APP_KEY    {0x01, 0x00, 0x00, 0x00, 0x00, 0x0D, 0x0C, 0x00, 0x0F, 0x00, 0x0E, 0x00, 0x00, 0x00, 0x00, 0x00 }

